### PR TITLE
Add logic to set the alt body from a view file

### PR DESCRIPTION
**Pull request by bopinto**
PHPMailer already strips the HTML body to set the alt body, but we may want to set it on our own.

### CODE REVIEW

**Comment by surfer190** [comment]
Sorry I opened an issue #28 before reading the pull requests

@vernes Could you review this pull request. @bopinto I will be using your repo for now.

**Comment by vernes** [comment]
Merged, thanks

**Comment by surfer190** [comment]
@vernes @bopinto I noticed that setting an `altBody`with something like:

```
$mail->altBody('Hello world');
```

doesn't matter as this value is overwritten no matter what.
I think the issue is in PHPMailer: the `msgHTML` function. 
The function docs says it:

```
Overwrites any existing values in $this->Body and $this->AltBody
```

**Comment by vernes** [comment]
Yes
https://github.com/PHPMailer/PHPMailer/blob/master/class.phpmailer.php#L3335-L3339

But using textView form this PR you can overide it after it renders html body

**Pull request merged**
